--Questions: Write queries to find out the following:

---1.	List all the states in which we have customers who have bought cellphones 
	--from 2005 till today.


SELECT STATE 
FROM FACT_TRANSACTIONS T1
INNER JOIN DIM_LOCATION T2 ON T1.IDLOCATION= T2.IDLOCATION
INNER JOIN DIM_MODEL T3 ON T1.IDMODEL= T3.IDMODEL
WHERE DAte BETWEEN '01-01-2005' AND GETDATE()



--2.	What state in the US is buying more 'Samsung' cell phones?

select* from DIM_LOCATION
select* from FACT_TRANSACTIONS
select* from DIM_CUSTOMER
select* from DIM_MODEL
select* from DIM_MANUFACTURER


SELECT TOP 1 
STATE FROM DIM_LOCATION AS L
INNER JOIN FACT_TRANSACTIONS AS T
ON L.IDLOCATION=T.IDLOCATION
INNER JOIN DIM_MODEL as M 
ON T.IDMODEL = M.IDMODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER= M.IDMANUFACTURER
WHERE MANUFACTURER_NAME = 'Samsung'
GROUP BY STATE
ORDER BY SUM(QUANTITY) DESC


--3.Show the number of transactions for each model per zip code per state.

SELECT MODEL_NAME, ZIPCODE, STATE, COUNT(IDCUSTOMER) AS NO_OF_TRANSACTIONS FROM DIM_LOCATION
INNER JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLOCATION=FACT_TRANSACTIONS.IDLOCATION
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
GROUP BY MODEL_NAME, ZIPCODE, STATE



--4.Show the cheapest cellphone

SELECT TOP 1
IDMODEL, MODEL_NAME FROM DIM_MODEL
ORDER BY UNIT_PRICE

--5.Find out the average price for each model in the top5 manufacturers in terms of sales quantity and order by average price.

SELECT MODEL_NAME, AVG(UNIT_PRICE) AS AVG_PRICE FROM DIM_MODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
WHERE MANUFACTURER_NAME IN 
(
SELECT TOP 5 MANUFACTURER_NAME FROM FACT_TRANSACTIONS
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(QUANTITY)
)
GROUP BY MODEL_NAME
ORDER BY AVG(UNIT_PRICE) DESC


--6.List the names of the customers and the average amount spent in 2009, where the average is higher than 500

SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AVG_SPENT
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS ON DIM_CUSTOMER.IDCUSTOMER = FACT_TRANSACTIONS.IDCUSTOMER
WHERE YEAR(Date) = 2009 
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE)>500

--7.List if there is any model that was in the top 5 in terms of quantity, simultaneously in 2008, 2009 and 2010

SELECT MODEL_NAME 
FROM FACT_TRANSACTIONS
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL= DIM_MODEL.IDMODEL
GROUP BY MODEL_NAME
HAVING 
SUM(QUANTITY) >= (SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(Date) = 2008  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC) AND 
SUM(QUANTITY) >= (SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(Date) = 2009  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC) AND 
SUM(QUANTITY) >= (SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(Date) = 2010  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC)


--8.Show the manufacturer with the 2nd top sales in the year of 2009 and the manufacturer with the 2nd top sales in the year of 2010.

SELECT TOP 1 MANUFACTURER_NAME 
FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(TOTALPRICE) DESC


--9.Show the manufacturers that sold cellphone in 2010 but didn’t in 2009.

SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2010 
EXCEPT 
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2009


--10.Find top 100 customers and their average spend, average quantity by each year.Also find the percentage of change in their spend.

SELECT TOP 100 CUSTOMER_NAME, 
AVG(CASE WHEN YEAR(Date) = 2005 THEN TOTALPRICE END) AS AVERAGE_PRICE_2005,
AVG(CASE WHEN YEAR(Date) = 2005 THEN QUANTITY END) AS AVERAGE_QTY_2005,
AVG(CASE WHEN YEAR(Date) = 2018 THEN TOTALPRICE END) AS AVERAGE_PRICE_2018,
AVG(CASE WHEN YEAR(Date) = 2018 THEN QUANTITY END) AS AVERAGE_QTY_2018
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS T1 ON T1.IDCUSTOMER= DIM_CUSTOMER.IDCUSTOMER
GROUP BY CUSTOMER_NAME
